site_name: Pure3D
site_description: >- 
  Pure3D: an infrastructure for digital scholarly editions

site_url: 'https://clariah.github.io/pure3d/'

site_author: Dirk Roorda

theme:
  name: mkdocs
  logo: 'images/pure3d.png'
  feature:
    tabs: false
repo_url: 'https://github.com/clariah/pure3d'

strict: false


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark

plugins:
  - markdownextradata
